### ISSUE TITLE
help with access token

### ISSUE THREAD

**Issue by nostorian** [InviteManagerBot/disco.oauth2#1]
so in your code it says we have to enter a code to avail the access token:
```py
access_token = await client.exchange_code("my_code")
```
but i am new to whole oauth2 stuff so do you mind telling me what should i enter as `'my code'`?

**Comment by martimartins** [comment]
"my_code" is used to exchange for a token. This token is provided by the [authorization code grant](https://discord.com/developers/docs/topics/oauth2#authorization-code-grant) flow, in a nutshell this flow consists of:
User Authorizes App -> Redirect to [redirect_url](https://discord.com/developers/docs/topics/oauth2#authorization-code-grant-redirect-url-example)

The redirect_url receives two parameters:
- code: Used to exchange for a access token.
- [state](https://discord.com/developers/docs/topics/oauth2#state-and-security): helps prevent [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery) attacks and represents your application's state.

Here's a simple example for [authorization code grant](https://discord.com/developers/docs/topics/oauth2#authorization-code-grant) using [aiohttp](https://github.com/aio-libs/aiohttp):
```py
import asyncio
import os

import disco_oauth2
from aiohttp import web

routes = web.RouteTableDef()


@routes.get("/start-flow")
async def start_flow(request: web.Request) -> web.StreamResponse:
    client: disco_oauth2.Client = request.app["client"]

    # Get the auth url with a random state and redirect
    auth_url = client.get_oauth_url(state=os.urandom(16).hex())

    return web.HTTPFound(auth_url)


@routes.get("/exchange-code")
async def exchange_code(request: web.Request) -> web.StreamResponse:
    client: disco_oauth2.Client = request.app["client"]

    # Get code from received parameters
    code: str = request.rel_url.query["code"]
    # Get state from received parameters
    state: str = request.rel_url.query["state"]

    # Exchange the code for a access token
    access_token: disco_oauth2.AccessToken = await client.exchange_code(code)

    # Fetch user's information
    user = await client.fetch_user(access_token)
    # Fetch user's guilds that he is member of
    guilds = await user.fetch_guilds()

    return web.Response(
        text=f"WoW got user information and token of {user!r}! Look at this:\n\n{access_token.access_token}\nGuilds: \n\n{', '.join(repr(x) for x in guilds)}"
    )


def init() -> None:
    # Create new event loop
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)

    client = disco_oauth2.Client(
        client_id=...,
        client_secret="...",
        redirect_uri="http://localhost:8000/exchange-code",
        scopes=["identify", "guilds", "email", "connections"],
    )
    app = web.Application()
    app["client"] = client
    app.add_routes(routes)
    web.run_app(app, host="localhost", port=8000, loop=loop)


if __name__ == "__main__":
    init()
```

I suggest you learn more about the OAuth2 protocol and familiarize yourself with it, here are links that may be useful for you:
- [Discord OAuth2 Docs](https://discord.com/developers/docs/topics/oauth2)
- [OAuth2.0 rfc](https://www.rfc-editor.org/rfc/rfc6749)
